services:
  app:
    image: your-app:latest
    build: .
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION_MIN=${JWT_ACCESS_EXPIRATION_MIN}
      - JWT_REFRESH_EXPIRATION_DAYS=${JWT_REFRESH_EXPIRATION_DAYS}
    ports:
      - "8080:8080"
    volumes:
      - app-logs:/app/logs
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: my_postgress
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  app-logs:
  postgres-data: