server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: logs/issuetracker.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
  level:
    com.t1.officebooking: INFO
    org.springframework.web: WARN
    org.hibernate: ERROR
